
public enum Type {
    PROC, IF, THEN, ELSE, DO, WHILE, REPEAT, FOR, TIMES, NOT,
    NORTH, SOUTH, WEST, EAST, FRONT, BACK, LEFT, RIGHT,
    MOVE, TURN, FACE, JUMP, DROP, PICK, GRAB, LET_GO, POP, NOP,
    PUT, BALLOONS, CHIPS,
    BLOCKED_Q, FACING_Q, ZERO_Q, CAN_MOVE, CAN_JUMP, CAN_PUT, CAN_PICK,
    VARIABLE, NUMBER, DIRECTION, POSITION, CONDITION, MACRO_NAME,
    ASSIGN, COMMA, SEMICOLON, LBRACE, RBRACE, LPAREN, RPAREN, EQUALS,
    ERROR, TOTHE, INDIR, OPEN_BRACKET, CLOSE_BRACKET, PERIOD, COLON;
}
